spring:
  rabbitmq:
    host: 192.168.0.105 # rabbitmq的连接地址
    port: 5672 # rabbitmq的连接端口号
    virtual-host: /ming # rabbitmq的虚拟host
    username: ming # rabbitmq的用户名
    password: ming # rabbitmq的密码
    publisher-confirm-type: correlated #publisher-confirms: true已弃用 如果对异步消息需要回调必须设置为true
